### ISSUE TITLE
call cv::VideoCapture vcap(filename)；

### ISSUE THREAD

**Issue by jgehry82** [nokiatech/heif#24] opened 2017-10-17 07:12 UTC
OpenCV: Couldn't read video stream from file "/Desktop/temp_bitstream.hevc"
cv::VideoCapture::isOpened returned false

**Comment by prepas** [comment] 2017-10-18 15:34
I have the same problem and I can't convert hevc to jpg format. The function
HevcImageFileReader::getDecoderParameterSets has wrong code, it works correct if remove these code:
{code}
    auto iter = mParameterSetMap.find(Id(contextId, itemId));
    if (iter != mParameterSetMap.end())
    {
        parameterSets = iter->second;
        return;
    }
{code}
Finally variant of function is:
{code}
void HevcImageFileReader::getDecoderParameterSets(const uint32_t contextId, const uint32_t itemId,
    ParameterSetMap& parameterSets) const
{
    isInitialized();

    // Was it an image/sample?
    const Id parameterSetId = mImageToParameterSetMap.at(Id(contextId, itemId));
	auto iter = mParameterSetMap.find(parameterSetId);
    if (iter != mParameterSetMap.end())
    {
        parameterSets = iter->second;
        return;
    }
    throw FileReaderException(FileReaderException::StatusCode::INVALID_ITEM_ID); // or invalid context...?
}
{code}
Please, remove these wrong code as soon as possibly

**Comment by prepas** [comment] 2017-10-20 08:13
@nokiatech can fix it? Please, see my comment above.

**Comment by prepas** [comment] 2017-11-13 13:57
@nokiatech any news?

**Comment by nokiatech** [comment] 2018-03-08 12:42
Duplicate of issue #9. Resolved in v3.0

**Closed by nokiatech** 2018-03-08 12:42 UTC
Labels: duplicate
